In [141]:
# Reload all modules (except those excluded by %aimport) every time before executing the Python code typed.
%load_ext autoreload
%autoreload 2
%matplotlib inline
import os
import collections
import matplotlib.pyplot as plt
from environment.main import PacMan
from matplotlib.animation import FuncAnimation
from IPython.display import HTML
# from a3c_cnn.main import a3c_demo

import argparse
import os
import torch
import torch.multiprocessing as mp

# from a3c_cnn.optimisation import SharedAdam
# from a3c_cnn.model import ActorCritic
# from a3c_cnn.test import test
# from a3c_cnn.train import train
# from a3c_cnn.policy import A3CPolicy
from environment.main import PacMan

from a3c2 import Net
from a3ctwo.policy import A3CTwo



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [142]:
game = PacMan(maze_row_num=2, maze_column_num=2, maze_row_height=2, maze_column_width=2)
game.random_reset()
game.generate_animation()
ani = HTML(game.animation.to_jshtml())
ani

Generated frames: 192

In [144]:
model = Net(100, 4)
state = torch.load('a3ctwo/1cnn_dropout_0.2_channel_4.pt')
model.load_state_dict(state['model_state_dict'])
game = PacMan(maze_row_num=2, maze_column_num=2, maze_row_height=2, maze_column_width=2)
policy = A3CTwo(model)
game.agent.set_policy(policy)
game.random_reset()
game.generate_animation()
ani = HTML(game.animation.to_jshtml())
ani

Generated frames: 11

In [148]:
from tqdm import tqdm
win = 0 
for i in tqdm(range(100)):
    game.random_reset()
    while not game.process.termination:
        game.run_one_step_without_graph()
    if game.process.win:
        win+=1
print(win)

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 70.76it/s]

0


In [511]:
model = ActorCritic()
checkpoint = torch.load('a3c_model_checkpoint')
model.load_state_dict(checkpoint['model_state_dict'])
game = PacMan(maze_row_num=2, maze_column_num=2, maze_row_height=2, maze_column_width=2)
policy = A3CPolicy(model)
game.agent.set_policy(policy)
game.random_reset()
game.generate_animation()
ani = HTML(game.animation.to_jshtml())
ani

Generated frames: 0tensor([[0.2473, 0.2464, 0.2458, 0.2604]], grad_fn=<SoftmaxBackward>)
3 (0, -1)
tensor([[-0.0034, -0.0068, -0.0093,  0.0485]], grad_fn=<AddmmBackward>)
Generated frames: 1tensor([[0.2505, 0.2488, 0.2472, 0.2536]], grad_fn=<SoftmaxBackward>)
3 (0, -1)
tensor([[ 0.0120,  0.0054, -0.0010,  0.0244]], grad_fn=<AddmmBackward>)
Generated frames: 2tensor([[0.2484, 0.2464, 0.2506, 0.2546]], grad_fn=<SoftmaxBackward>)
3 (0, -1)
tensor([[-0.0038, -0.0118,  0.0049,  0.0209]], grad_fn=<AddmmBackward>)
Generated frames: 3tensor([[0.2443, 0.2492, 0.2533, 0.2533]], grad_fn=<SoftmaxBackward>)
3 (0, -1)
tensor([[-0.0238, -0.0040,  0.0122,  0.0123]], grad_fn=<AddmmBackward>)
Generated frames: 4tensor([[0.2388, 0.2518, 0.2517, 0.2577]], grad_fn=<SoftmaxBackward>)
3 (0, -1)
tensor([[-0.0364,  0.0164,  0.0160,  0.0395]], grad_fn=<AddmmBackward>)
Generated frames: 5tensor([[0.2457, 0.2489, 0.2515, 0.2539]], grad_fn=<SoftmaxBackward>)
3 (0, -1)
tensor([[-0.0176, -0.0049,  0.0054,  0.0152]],

In [166]:
print(game.agent.policy.model == model)

True


In [501]:
test = ActorCritic()

In [473]:
test.eval()

ActorCritic(
  (conv1): Conv2d(1, 2, kernel_size=(2, 2), stride=(1, 1))
  (conv2): Conv2d(2, 2, kernel_size=(2, 2), stride=(1, 1))
  (critic_linear): Linear(in_features=50, out_features=1, bias=True)
  (actor_linear): Linear(in_features=50, out_features=4, bias=True)
)

In [500]:
test((torch.rand(1,1,7,7),(1,1)))

(tensor([[0.5338]], grad_fn=<AddmmBackward>),
 tensor([[0.0067, 0.0088, 0.0096, 0.0055]], grad_fn=<AddmmBackward>),
 (1, 1))

In [ ]:
test((torch.from_numpy(game.synthetic_array).unsqueeze(0).unsqueeze(0).float(),(1,1)))

In [707]:
# Reload all modules (except those excluded by %aimport) every time before executing the Python code typed.
%load_ext autoreload
%autoreload 2
%matplotlib inline
import os
import collections
import matplotlib.pyplot as plt
from environment.main import PacMan
from matplotlib.animation import FuncAnimation
from IPython.display import HTML
# from a3c_cnn.main import a3c_demo

import argparse
import os
import torch
import torch.multiprocessing as mp

from a3c_cnn.optimisation import SharedAdam
from a3c_cnn.model import ActorCritic
from a3c_cnn.test import test
from a3c_cnn.train import train
from a3c_cnn.policy import A3CPolicy
from environment.main import PacMan

from a3c2 import Net
from a3ctwo.policy import A3CTwo
model = Net(144, 4)
model.eval()
checkpoint = torch.load('a3c2_model_checkpoint_with_3cnn')
model.load_state_dict(checkpoint['model_state_dict'])
game = PacMan(maze_row_num=2, maze_column_num=2, maze_row_height=2, maze_column_width=2)
policy = A3CTwo(model)
game.agent.set_policy(policy)
game.random_reset()
game.generate_animation()
ani = HTML(game.animation.to_jshtml())
print('\n',game.process.reward)
ani

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Generated frames: 0
 0
Generated frames: 1
 2
Generated frames: 2
 0
Generated frames: 3
 2
Generated frames: 4
 5
